source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'font-awesome-rails'
gem 'bootstrap-sass'
gem 'rails-assets-angular', '~> 1.2.0'
gem 'rails-assets-angular-route', '~> 1.2.0'
gem 'rails-assets-angular-resource', '~> 1.2.0'
gem 'rails-assets-angular-animate', '~> 1.2.0'
gem 'rails-assets-angular-ui-bootstrap-bower', '~> 0.12.0'
gem 'rails-assets-angular-xeditable'
gem 'rails-assets-ng-sortable'
gem 'ransack'
gem 'kaminari'
gem 'acts_as_list'
gem 'slim-rails'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'pry', '< 0.10.0'
  gem 'pry-rails'
  gem 'hirb'
  gem 'hirb-unicode'
end
